### ISSUE TITLE
How to get data from Google Maps

### ISSUE THREAD

**Issue by Albertolopezs** [Corvince/mesa-geo#12]
Hi, I´m trying to get data from roads to draw it and analize it's traffic, i had been searching for a long but i can't afford a way to get JSON or GeoJSON. Anyone could help me?

**Comment by Corvince** [comment]
Hi there,

I don't think you can get road data from google maps. But OpenStreetMap has excellent road data which is availabe, see [Downloading data](https://wiki.openstreetmap.org/wiki/Downloading_data)
Traffic data is more difficult. See [this question](https://stackoverflow.com/questions/4600656/access-googles-traffic-data-through-a-web-service) for some advice (e.g. HERE traffic data)

I leave this issue open a bit more, but will close it eventually, since it is not an issue with GeoMesa. I think you are better off asking at different places (e.g. [Stack Overflow](https://stackoverflow.com/))
